### PR TITLE
uplift bouncy castle crypto library version

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-managers-pr-883-kslv5 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-managers-pr-883-4wvgm for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Review by AaronJhaj — COMMENTED** [review]
Do we also need to update the versions in dev.galasa.zossecurity.manager/build.gradle ?

**Review by AaronJhaj — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
