### PR TITLE
Zos batch

### PR DESCRIPTION
**Pull request by hobbit1983**

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by hobbit1983** [comment]
So this PR fixes the following problems when using the SEM manager to provision a CICS:
* All spool output was just stored in a single directory with no structure
* A lot of the stored spool files were empty - made debugging a lot of fun

This fixes all of that across the zosMF and RSE batch implementations

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by techcobweb — APPROVED** [review]
Looks good. Sorry I didn't get to it earlier today.

**Comment by hobbit1983** [comment]
Thank you @techcobweb

**Pull request merged**
