### PR TITLE
re-build release.yaml from the managers in the source tree.

### PR DESCRIPTION
**Pull request by techcobweb**
- [x] new script `set-version.sh` which re-builds release.yaml from all the data now sited in each manager settings.gradle. 

Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by hobbit1983 — APPROVED** [review]

**Pull request merged**
