### PR TITLE
3270 terminals disconnect and re-connect between scenarios

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

# Why ?

See https://github.com/galasa-dev/projectmanagement/issues/1858

To get multiple scenarios working within a single feature, it is necessary to disconnect terminals when the scenario (method) has finished.

Hooking into the endMethod call, so that all connected terminals can be disconnected for gherkin test cases.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
