### PR TITLE
Holly upgrade java

### PR DESCRIPTION
**Pull request by Wyvinar**
# Why
Java is outdated on this branch, upgrading to latest version, relates to: https://github.com/galasa-dev/projectmanagement/issues/1823

### CODE REVIEW

**Comment by Wyvinar** [comment]
this is a mess :D I don't know how to use gradle, so good luck sorting everything

**Comment by Wyvinar** [comment]
```
* What went wrong:
A problem occurred evaluating project ':galasa-managers-testingtools-parent:dev.galasa.sdv.manager'.
> Cannot have two attributes with the same name but different types. This container already has an attribute named 'org.gradle.jvm.environment' of type 'org.gradle.api.attributes.java.TargetJvmEnvironment' and you are trying to store another one of type 'java.lang.String'
```

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-managers-pr-951-5vgn6 for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by Mark-J-Lawrence** [comment]
> ```
> * What went wrong:
> A problem occurred evaluating project ':galasa-managers-testingtools-parent:dev.galasa.sdv.manager'.
> > Cannot have two attributes with the same name but different types. This container already has an attribute named 'org.gradle.jvm.environment' of type 'org.gradle.api.attributes.java.TargetJvmEnvironment' and you are trying to store another one of type 'java.lang.String'
> ```
> 
> there is in fact only one variable named that, and it did seem to be working before. Do you know anything about this @Mark-J-Lawrence ?

@Wyvinar This is the recently included SDV Manager barfing, probably due to this line https://github.com/galasa-dev/managers/blob/294c6ef3ccde1fbb0c9b58a100dff3a0d7590b5c/galasa-managers-parent/galasa-managers-testingtools-parent/dev.galasa.sdv.manager/build.gradle#L18

I had to add this line because the `checkstyle` tool ran as part of the SDV build had issues running on Gradle 6.x without it. Which leaves two options i think:

1. Upgrade to using Gradle 7.x or higher for the managers build in your Tekton pipeline
2. Remove checkstyle from the SDV build

**Pull request closed without merging**
