### PR TITLE
Minor edits to artifact mgr snippets and pkginfo

### PR DESCRIPTION
**Pull request by CaroMac**

### CODE REVIEW

**Comment by hobbit1983** [comment]
@CaroMac on line 7 of code-snippets could you change the declaration of IBundleResources to be public. That’s my error but would save me creating a PR for a single word change. Thank you

**Comment by CaroMac** [comment]
Sure, done.

**Comment by hobbit1983** [comment]
@CaroMac you need to sign the DCO for this PR to pass the check.  This is a fairly new thing that we have implemented.  More information can be found here: https://github.com/apps/dco

**Comment by CaroMac** [comment]
oh yes, read the link. that is helpful thank you. will do it next time.

**Pull request merged**
