### PR TITLE
Update io.kubernetes:client-java to 16.0.2

### PR DESCRIPTION
**Pull request by eamansour**
For https://github.com/galasa-dev/projectmanagement/issues/1092

- Updated `io.kubernetes:client-java` from 14.0.0 to the latest version (16.0.2), removing several vulnerabilities.
- Minor code changes were needed to resolve compilation errors as an optional `fieldValidation` parameter was added to several CoreV1API methods in a post-14.0.0 version of `io.kubernetes:client-java`.

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by jadecarino — APPROVED** [review]

**Review by techcobweb — APPROVED** [review]
Looking good to me.

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-managers-pr-823-v8pn8 for details

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
