### PR TITLE
gradle constructs the release.yaml and publishes it

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

- Fix to set-version.sh to uplift the version of the framework in a dependency.
- the gradle build now builds the release.yaml file, and puts it into maven:
image
- (I have a PR for the OBR project I want to try after, which pulls the release.yaml from maven rather than cloning the managers repo and digging it out of the release.yaml file).
- Left the release.yaml file in git for now, will need removing once the OBR uses the maven version.

The file contains this:
```
#
# Copyright contributors to the Galasa project 
#

# -----------------------------------------------------------
#
#                         WARNING
#
# This file is periodically re-generated from the contents of 
# the repository, so don't make changes here manually please.
# -----------------------------------------------------------


apiVersion: galasa.dev/v1alpha
kind: Release
metadata:
  name: galasa-release
    
managers:
  bundles:

#
# Manager 
#


  - artifact: dev.galasa.cicsts.ceci.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.cicsts.ceci.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.cicsts.ceda.manager
    version: 0.29.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.cicsts.ceda.manager.ivt
    version: 0.22.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.cicsts.cemt.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.cicsts.cemt.manager.ivt
    version: 0.22.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.cicsts.manager
    version: 0.28.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.cicsts.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     false
    codecoverage: false

  - artifact: dev.galasa.cicsts.resource.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.cloud.manager
    version: 0.22.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.docker.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.docker.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.kubernetes.manager
    version: 0.29.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.kubernetes.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.liberty.manager
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.openstack.manager
    version: 0.26.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.common
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.http.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.http.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.ipnetwork.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.mq.manager
    version: 0.25.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: 
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.artifact.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.artifact.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.core.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.core.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.textscan.manager
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.db2.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.db2.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.eclipseruntime.manager
    version: 0.18.0
    obr:          false
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     false
    codecoverage: false

  - artifact: dev.galasa.eclipseruntime.ubuntu.manager
    version: 0.18.0
    obr:          false
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     false
    codecoverage: false

  - artifact: dev.galasa.sem.manager
    version: 0.25.0
    obr:          false
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     false
    codecoverage: false

  - artifact: dev.galasa.java.manager
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.java.ubuntu.manager
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.java.windows.manager
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.elasticlog.manager
    version: 0.25.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.elasticlog.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.phoenix2.manager
    version: 0.25.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.galasaecosystem.manager
    version: 0.27.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.galasaecosystem.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.jmeter.manager
    version: 0.25.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.jmeter.manager.ivt
    version: 0.25.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.selenium.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.selenium.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.vtp.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.vtp.manager.ivt
    version: 0.21.0
    obr:          false
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     false
    codecoverage: false

  - artifact: dev.galasa.linux.manager
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.linux.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.windows.manager
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.githubissue.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.zos.manager
    version: 0.28.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zos.manager.ivt
    version: 0.28.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.zos3270.common
    version: 0.28.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      true
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.zos3270.manager
    version: 0.28.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zos3270.manager.ivt
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          false
    javadoc:      false
    isolated:     true
    codecoverage: false

  - artifact: dev.galasa.zosbatch.rseapi.manager
    version: 0.26.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosbatch.zosmf.manager
    version: 0.26.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosconsole.oeconsol.manager
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosconsole.zosmf.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosfile.rseapi.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosfile.zosmf.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosliberty.angel.manager
    version: 0.21.0
    obr:          true
    mvp:          false
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosliberty.manager
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosmf.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosprogram.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosrseapi.manager
    version: 0.25.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zossecurity.manager
    version: 0.29.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      true
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zostsocommand.ssh.manager
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true

  - artifact: dev.galasa.zosunixcommand.ssh.manager
    version: 0.21.0
    obr:          true
    mvp:          true
    bom:          true
    javadoc:      false
    isolated:     true
    codecoverage: true
```

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-managers-pr-885-mv2gs for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-managers-pr-885-g4pgh for details. If you are unable to do so, please contact a member of the Galasa team.

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by KirbyKatcher — APPROVED** [review]

**Pull request merged**
