### PR TITLE
fail sooner if user ID revoked

### PR DESCRIPTION
**Pull request by Mark-J-Lawrence**
when logging in, if a user ID has been revoked, the code sits and waits till time out.

Added the revoked message to fail the run sooner

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by Mark-J-Lawrence** [comment]
@hobbit1983 This is one of the PRs I mentioned

**Comment by techcobweb** [comment]
Approved for building

**Review by techcobweb — APPROVED** [review]
Approved for building

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
