### PR TITLE
Use a valid character for Windows path in archive name

### LINKED ISSUE #805: Unable to log message for a queue java.nio.file.InvalidPathException: Illegal char <:>
When the MQ manager is used on Windows, we are getting the following error message:

```
5/08/2022 14:34:32.695 INFO  main [dev.galasa.mq](http://dev.galasa.mq/).internal.MessageQueueImpl.archiveMessage - Unable to log message for a queue
java.nio.file.InvalidPathException: Illegal char <:> at index 51: mq/messages/clearQueue/RAFDA.TESTQ/outbound/message:4
```

The queue is declared as:
```
	@Queue(archive = true, name = "RAFDA.TESTQ", queueMgrTag = "PRIMARY")
	public IMessageQueue queue;
```

When `archive = false`, the problem does not occur.
The same code works well on macOS. It seems that `:` that is used in the path for archiving is not valid in the Windows path. Replacing it with a different character can be a good solution.

### PR DESCRIPTION
**Pull request by plavjanik**
Fixes #805 by using a `_` that is a valid character in Windows paths.

Note: My editor trims whitespace automatically (if that is an issue, I will switch it off).

Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>

### CODE REVIEW

**Comment by cicsdeliverytest** [comment]
Can one of the admins verify this patch?

**Comment by Jimbo4794** [comment]
Approved

**Comment by plavjanik** [comment]
How can I get the Tekton build to be kicked off?

**Comment by Jimbo4794** [comment]
My comment earlier was suppose to do that. Let me investigate

**Comment by Jimbo4794** [comment]
Build started, build trigger prhased had changed. Sorry about that

**Comment by Jimbo4794** [comment]
An FYI, the details link on the Tekton job will soon be publically accessible. If there are any issues with that build ill let you know what the output is atm

**Comment by plavjanik** [comment]
Thank you. I see the build to be completed but when I try to open the link (https://[ejat-phoenix-tooling-jenkins.swg-devops.com](https://ejat-phoenix-tooling-jenkins.swg-devops.com/job/Galasa/job/Pull_Requests/job/PR_Managers/479/)/job/Galasa/job/Pull_Requests/job/PR_Managers/479/), it times out.

What is the easiest way how to run all the tests before opening PR?

**Comment by Jimbo4794** [comment]
Yeah that link is behind IBM firewall. Im currrently working on migrating the entire build stack outside of IBM so we can have a true open source air gap. I will probably put an annoucement in the Slack channel when that goes live

**Review by galasa-team — APPROVED** [review]
This is my fault! - thank you very much for fixing.  Approved

**Comment by galasa-team** [comment]
I will need to add a follow on change to bump the MQ manager to 0.25.0 so this will get released

**Pull request merged**
