### PR TITLE
Added tests to ArtifactManagerIVT

### PR DESCRIPTION
**Pull request by james-ashman**
Created several test for ArtifactManagerIVT as well as tidied up some existing tests. 

Signed-off-by: James Ashman <James.ashman@ibm.com>

### CODE REVIEW

**Comment by cicsdeliverytest** [comment]
Can one of the admins verify this patch?

**Comment by hobbit1983** [comment]
rerun tests

**Comment by hobbit1983** [comment]
run tests

**Review by hobbit1983 — APPROVED** [review]

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by hobbit1983** [comment]
rerun tests

**Comment by hobbit1983** [comment]
re run tests

**Pull request closed without merging**
