### PR TITLE
Fix: consolidated jvmserverimpl constructor

### PR DESCRIPTION
**Pull request by Tom-Slattery**
JVMServerImpl constructor previously would get a null pointer. I have consolidated the shared code between the three constructors into one method which is run by each constructor. Fixed null pointer in handling of JVMProfile,

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Review by hobbit1983 — APPROVED** [review]

**Comment by techcobweb** [comment]
@Tom-Slattery did you mean to merge this one in ?

**Comment by galasa-team** [comment]
Build successful

**Comment by techcobweb** [comment]
Tom said he did, so I sorted it and merged on his behalf.

**Pull request merged**
