### PR TITLE
Initial TPI/SPI of the CICS TS Manager so we can work on the DSE/SEM …

### PR DESCRIPTION
**Pull request by Michael-Baylis**
…end-to-end provisioning

quick review of the SPI/TPI to make sure there is nothing glaringly wrong.   This is the minimum required to allow Michael to start work on the DSE and SEM provisioning

Signed-off-by: Michael Baylis <Michael.Baylis@uk.ibm.com>

### CODE REVIEW

**Comment by hobbit1983** [comment]
Where is the ProductVersion class.  I can see it referenced

**Comment by Michael-Baylis** [comment]
> I can't see dev.galasa.ProductVersion class in this commit. (that could just be me). Also is there some inconsistency with sometimes adding `ts` as a suffix to `Cics` and sometimes not.

Because it is in dev.galasa   in the framework repo

**Comment by Michael-Baylis** [comment]
> I can't see dev.galasa.ProductVersion class in this commit. (that could just be me). Also is there some inconsistency with sometimes adding `ts` as a suffix to `Cics` and sometimes not.

@wyates as for cics,  ICics should be the only one called cics,   everything else is cicsts because that was what the manager was called before I got to it

**Comment by Michael-Baylis** [comment]
@hobbit1983 sorry, should be clearer,   anything related to the CICS Region, is CICS,  anything to do with the Manager etc,  is CICS TS

**Comment by Michael-Baylis** [comment]
grr,  you are right

**Comment by Michael-Baylis** [comment]
ICics and @Cics has been renamed to ICicsRegion and @CicsRegion to future proof against collisions with other CICS products

**Pull request merged**
