### PR TITLE
Add support for Read Partition Type code = 3

### PR DESCRIPTION
**Pull request by Jakub-CZ**
Resolves https://github.com/galasa-dev/projectmanagement/issues/165

### CODE REVIEW

**Comment by cicsdeliverytest** [comment]
Can one of the admins verify this patch?

**Comment by hobbit1983** [comment]
Hey @Jakub-CZ thanks very much for the PR.  really appreciate you adding code to the community.  I will ask Michael Baylis to check this code as he knows it a lot better than I.  However he is not back till Tuesday.  I hope that's OK.  Again Thank You

**Comment by hobbit1983** [comment]
@Jakub-CZ I've let Mike know and he will take a look tomorrow.  Thanks again

**Comment by Michael-Baylis** [comment]
run tests

**Comment by Michael-Baylis** [comment]
Looks good.   Will test on Tuesday as on holiday for Easter.   Need to figure out why Jenkins didn't take the "run tests".

**Comment by hobbit1983** [comment]
@Jakub-CZ as Mike says we've reviewed your code and are very impressed with it so will likely to commit.  However there are a few things we need to ask of you (sorry)
1) can you sign your commit using a GPG key please.  We've been doing this for a while.  More information to set this up is here: https://help.github.com/en/github/authenticating-to-github/signing-commits
2) Can you review the DCO that is here https://github.com/galasa-dev/managers/blob/master/CONTRIBUTIONS.md. We will turn on the DCO app on Tuesday (public holidays in the UK) to allow both you and the IBM team to sign the DCO for each commit (-s flag on all commits)

When all that is in place we will probably accept the PR, which in all honesty looks really good.  Thank you for contributing to the Galasa code base, if you need any help setting up the GPG signing or the DCO please let us know and we will help out

**Comment by Michael-Baylis** [comment]
ok to test

**Comment by Jakub-CZ** [comment]
Done and done. Hope the force-push won't break anything.

Until now, I didn't know what the sign-off feature was good for, it seemed almost pointless. Now that I read up on that a bit I understand.

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
finally getting there

**Pull request merged**
