### PR TITLE
Savvas ssltls

### PR DESCRIPTION
**Pull request by KirbyKatcher**

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-managers-pr-832-stsjx for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-managers-pr-832-ksn4b for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-managers-pr-832-gr7fp for details

**Comment by hobbit1983** [comment]
re run tests

**Review by hobbit1983 — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-managers-pr-832-gfmbc for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-managers-pr-832-fng98 for details

**Pull request closed without merging**
