### PR TITLE
CECI interfaces

### PR DESCRIPTION
**Pull request by DavidXRoberts**

### CODE REVIEW

**Comment by DavidXRoberts** [comment]
rerun tests

**Comment by DavidXRoberts** [comment]
@hobbit1983 The background to the enforced "&" is to distinguish between a variable name and a command. It's necessary to keep the terminal in a CECI session between invocations so that the test can issue multiple commands that depend on each other. There isn't enough space on the command line for anything other that the most basic of commands. Therefore, issueCommand() stores the supplied command in a variable and then executes the variable by entering the variable name on the command line. The test can also supply a variable containing a command to issueCommand() and it knows not to store it, but to execute it directly. Also, if a test were to create variables without "&" (with the manager adding it) and the test used them as values in a command (without the "&"), CECI would interpret them as character strings.

I was thinking about what should be returned from issueCommand() on the way to work this morning, and I agree that EIB is wrong.  More likely, the test will want the command response values from the screen.  So I going to change the return to ICECIResponse which will contain EIBRESP, EIBRESP2 and a Map of parameter/values.

**Comment by Michael-Baylis** [comment]
I agree with Will.   the & should not be needed for the set and get variables.   It will still be needed if referenced in the issueCommands.
setVariable(.. "BOB")
issueCommand(....  "&BOB")

**Comment by Michael-Baylis** [comment]
The only other thing I would like changed,  (without actually playing with it) is:-

if (!eib.getResponse().equals("NORMAL"))

cant we have:-

if (eib.isNormal())

much nicer for the tester

**Comment by Michael-Baylis** [comment]
I have approved,  so the code can go up.   but the TPI needs a little more work and the opportunity for me to play with it

**Pull request merged**
