### PR TITLE
mcobbett bump version

### PR DESCRIPTION
**Pull request by techcobweb**
- managers.manifest maven artifact created
- fixed bug in mq.managers.ivt build.gradle

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by AaronJhaj — APPROVED** [review]

**Pull request merged**
