### PR TITLE
overload deleteJson to provide a body

### PR DESCRIPTION
**Pull request by Mark-J-Lawrence**
Overloading the `deleteJson()` function so that a body can be provided for an HTTP `DELETE` request.

The [HTTP specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) state a body *may* be provided, however the Galasa code doesn't support this.

For the SDV manager I'm currently writing, I have a need to provide a JSON payload to a DELETE endpoint, therefore I'm adding it in as an overloaded function, so that existing functionality is not broken.

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by Mark-J-Lawrence** [comment]
@hobbit1983 @Jimbo4794 @eamansour please could you add the necessary text for this PR to build and assign an appropriate reviewer? I don't have permissions to do so, thanks

**Comment by Mark-J-Lawrence** [comment]
Closing this as after testing I've realised its not going to be possible as the code uses `org.apache.http.client.methods.HttpDelete` which I think does not allow body's as part of a DELETE

**Pull request closed without merging**
