### PR TITLE
Implemented PATCH request support

### PR DESCRIPTION
**Pull request by haripra86**
https://github.com/galasa-dev/projectmanagement/issues/1951

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Review by techcobweb — APPROVED** [review]

**Comment by techcobweb** [comment]
Approved for building

**Comment by techcobweb** [comment]
Approved for building

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by techcobweb** [comment]
Approved for building

**Review by techcobweb — CHANGES_REQUESTED** [review]
You need to bump the version of the plugin up to 0.36.0 in the build.gradle file version = "0.36.0".

Otherwise your change won't get used or distributed.

**Comment by haripra86** [comment]
> @haripra86 You need to bump the version of the plugin up to 0.36.0 in the build.gradle file version = "0.36.0". Beyond that it all looks good.
> 
> Otherwise your change won't get used or distributed.

You mean build.gradle of httpmanager module only or manager parent ?

**Comment by techcobweb** [comment]
Approved for building

**Comment by techcobweb** [comment]
> > @haripra86 You need to bump the version of the plugin up to 0.36.0 in the build.gradle file version = "0.36.0". Beyond that it all looks good.
> > Otherwise your change won't get used or distributed.
> 
> You mean build.gradle of httpmanager module only or manager parent ?

I mean the httpmanager. I think it's probably wise to bump the parent also, though the parent project doesn't really matter I believe, as it's just a grouping mechanism.

**Comment by techcobweb** [comment]
We are about to start releasing v0.36.0, so you may have to uplift those changes to v0.37.0 instead if this PR doesn't go in in the next day or so.

**Comment by techcobweb** [comment]
Do you want me to do the version bump-up if you don't feel comfortable doing it ?

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by haripra86** [comment]
> Do you want me to do the version bump-up if you don't feel comfortable doing it ?

@techcobweb I have uplifted httpmanager version to 0.36.0

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Review by techcobweb — APPROVED** [review]

**Comment by techcobweb** [comment]
Approved for building

**Comment by haripra86** [comment]
@techcobweb There is one commit marked as unverified and hence merging is blocked for me.

**Comment by galasa-team** [comment]
Build successful

**Comment by techcobweb** [comment]
I took the liberty of merging this PR into main, so it will be shipped as part of the 0.36.0 release this week (hopefully).

I realise that contributing to Galasa isn't the easiest. We are planning to change things to make it far easier, github actions, a single mono-repo. So hopefully this will get better.

On behalf of the Galasa project, thanks very much for your contribution.

-Mike.

**Pull request merged**
