### PR TITLE
Additional tests for HttpManagerIVT

### PR DESCRIPTION
**Pull request by jamesabdulrahman**
Added extra tests to check SSL context is properly set and to check that exceptions are thrown for requests with invalid query strings.

### CODE REVIEW

**Comment by cicsdeliverytest** [comment]
Can one of the admins verify this patch?

**Review by hobbit1983 — APPROVED** [review]

**Comment by jamesabdulrahman** [comment]
run tests

**Comment by jamesabdulrahman** [comment]
run tests

**Comment by hobbit1983** [comment]
rerun tests

**Comment by hobbit1983** [comment]
rerun tests

**Pull request closed without merging**
