### PR TITLE
fix to zosBatch 

### PR DESCRIPTION
**Pull request by hobbit1983**
zosBatch doesn't honour archiveOutput() if the output hasn't been retrieved

### CODE REVIEW

**Comment by hobbit1983** [comment]
rerun tests

**Comment by hobbit1983** [comment]
rerun tests

**Comment by hobbit1983** [comment]
rerun tests

**Comment by hobbit1983** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
rerun tests

**Pull request merged**
