### PR TITLE
Fix for 671 retrieveJar method

### PR DESCRIPTION
**Pull request by james-ashman**
Signed-off-by: James Ashman <james.ashman@ibm.com>

### CODE REVIEW

**Comment by cicsdeliverytest** [comment]
Can one of the admins verify this patch?

**Comment by james-ashman** [comment]
fixes galasa-dev/projectmanagement#671

**Review by hobbit1983 — APPROVED** [review]

**Comment by hobbit1983** [comment]
run tests

**Comment by hobbit1983** [comment]
re run tests

**Pull request merged**
